/** Maps form fieldId → Prisma Cliente column name */
export const FIELD_MAP: Record<string, string> = {
  nome: 'nome',
  responsavel: 'responsavel',
  negocio: 'negocio',
  servicos: 'servicos',
  cidade: 'cidade',
  estado: 'estado',
  publico: 'publico',
  site: 'site',
  url_site: 'urlSite',
  instagram: 'instagram',
  whatsapp: 'whatsapp',
  pixel: 'pixel',
  objetivo: 'objetivo',
  orcamento: 'orcamento',
  historico: 'historico',
  resultado_esperado: 'resultadoEsperado',
  criativos: 'criativos',
  descricao_criativos: 'descricaoCriativos',
  lista_clientes: 'listaClientes',
  oferta: 'oferta',
  diferencial: 'diferencial',
  comunicacao: 'comunicacao',
  frequencia: 'frequencia',
  observacoes: 'observacoes',
}
